# Generated by Django 5.1.3 on 2025-02-24 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_alter_cart_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("id",),
                "verbose_name": "Корзину",
                "verbose_name_plural": "Корзина",
            },
        ),
    ]
